language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
  - redis
install:
  - make install NPM_REGISTRY="" 
  - cp conf/default.json conf/test.json
script: make test
after_success:
  - echo OK